name: outfiti
description: AI outfit try-on

publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  image: ^4.0.17
  path_provider: ^2.1.1
  curved_navigation_bar: ^1.0.6
  shared_preferences: ^2.2.2
  cupertino_native: ^0.1.1
  device_info_plus: ^10.1.0
  flutter_animate: ^4.5.0
  animations: ^2.1.0
  http: ^1.2.0
  flutter_svg: ^2.0.9
  gal: ^2.3.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.2
  firebase_storage: ^12.3.8
  cloud_functions: ^5.1.3
  firebase_app_check: ^0.3.1+4
  in_app_review: ^2.0.9
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3
  photo_manager: ^3.6.0
  share_plus: ^10.1.4
  purchases_flutter: ^8.1.0
  video_player: ^2.9.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/outfit_samples/
    - assets/videos/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#1A1625"
  adaptive_icon_foreground: "assets/icons/logo.png"
